version: '3'

services:
  db:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=kadmos_saving_b
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 5433:5432

  savings-b:
    container_name: savings-b
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    image: savings-b:latest
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kadmos_saving_b
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=password
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update