#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
  \connect $APP_DB_NAME $APP_DB_USER
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
  BEGIN;
  CREATE TABLE SAVINGS_ACCOUNT (
    id uuid DEFAULT uuid_generate_v4(),
    account varchar(255) NOT NULL,
    amount NUMERIC(1000) NOT NULL,
    PRIMARY KEY (id)
  );
  INSERT INTO SAVINGS_ACCOUNT VALUES (uuid_generate_v4(), 'a', 100);
  INSERT INTO SAVINGS_ACCOUNT VALUES (uuid_generate_v4(), 'b', 500);
  COMMIT;
EOSQL
